### PR TITLE
chore(deps)!: Bump version of prometheus-elasticsearch-exporter to 6.5.0

### PR DESCRIPTION
**Pull request by cospeedster**
Bumped version to for example allow setting `revisionHistoryLimit` for elasticsearch-exporter.

### CODE REVIEW

**Comment by thomas-2020** [comment]
Hi @cospeedster,
did you test the new version of  prometheus-elasticsearch-exporter 6.5.0? It is possible to apply the new Helm Chart version without any "pre-migration" steps?

**Comment by cospeedster** [comment]
Hi @thomas-2020,

thanks for your question. I did a diff and this diff seemed to work. But after reading the [notes on 6.0.0](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter#to-600) and testing a `helm upgrade` locally I've found out that there is an "pre-migration" step:

"As the change is affecting immutable selector labels, the deployment must be deleted before upgrading the release, e.g.:
`kubectl delete deploy -l app=prometheus-elasticsearch-exporter`" (see [notes on 6.0.0](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter#to-600))

Here is an excerpt of my `helm upgrade`:

```
helm upgrade apigw ~/github/webmethods-helm-charts/apigateway/helm/ --values ~/<redacted>-default.yaml --values ~/<redacted>.yaml -n <redacted> --atomic --wait
Error: UPGRADE FAILED: release apigw failed, and has been rolled back due to atomic being set: cannot patch "apigw-es-prometheus-exporter" with kind Deployment: Deployment.apps "apigw-es-prometheus-exporter" is invalid: [spec.template.metadata.labels: Invalid value: map[string]string{"access-elasticsearch":"true", "app.kubernetes.io/component":"elasticsearch-exporter", "app.kubernetes.io/instance":"apigw", "app.kubernetes.io/name":"elasticsearch-exporter", "app.kubernetes.io/part-of":"api-gateway", "service-name":"elasticsearch-exporter", "service-type":"elasticsearch-exporter"}: `selector` does not match template `labels`, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"apigw", "app.kubernetes.io/name":"prometheus-elasticsearch-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]
```

So I decided to update my PR to generate a new chart major version because of a deployment breaking change.

I think we've to describe the "pre-migration" step in a readme.

What do you think?

**Comment by cospeedster** [comment]
For more discussion on that see #116

**Comment by cospeedster** [comment]
Hello @thomas-2020,

do you have any updates? Is there something I can help with?

              So, I have cloned your branch and will test the migration in my test environment

_Originally posted by @thomas-2020 in https://github.com/SoftwareAG/webmethods-helm-charts/issues/116#issuecomment-2489181490_

**Pull request merged**
